modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Bandit-bytes/Hyrule_terrors/issues"
license = "ALL RIGHTS RESERVED"
logoFile = "assets/hyrule_terrors/icon.png"

[[mods]]
modId = "hyrule_terrors"
version = "${version}"
displayName = "Hyrule Terrors"
authors = "Bandit-Bytes"
description = '''
A mod that adds creatures, structures, armors, and items inspired by The Legend of Zelda.
'''
#logoFile = ""

[[dependencies.hyrule_terrors]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "azurelib"
type = "required"
versionRange = "[3.0.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "hyrule_terrors.mixins.json"
