modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hyrule_terrors"
version = "${version}"
displayName = "Hyrule Terrors"
authors = "Bandit-Bytes"
description = '''

'''
#logoFile = ""

[[dependencies.hyrule_terrors]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "azurelib"
type = "required"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hyrule_terrors]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "hyrule_terrors.mixins.json"
